spring.application.name=Diagnostic-Center

spring.datasource.driver-class-name=${DRIVER_CLASS_NAME}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${SERVER_PORT}
jwt.secret.key = ${JWT_SECRET_KEY}

#Access Token 15 mins
jwt.access.token.expiration = 900000

#Password Token 30 mins
password.setOrReset.token.expiration = 30

#refresh token 7 days
jwt.refresh.token.expiration = 604800000


# Changing Envers audit table suffix to _history
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_history

spring.jpa.properties.org.hibernate.envers.global_with_modified_flag=true
spring.jpa.properties.org.hibernate.envers.modified_flag_suffix=_CHANGED